### ISSUE TITLE
i just re-invented code-red as sveltePreval.js

### ISSUE THREAD

**Issue by milahu** [Rich-Harris/code-red#23]
.... just using a different syntax

my design goal was:
avoid template literals, and use functions instead

the `preval` function takes a function as only argument
runs that function without arguments
and the [sveltePreval.js](https://gist.github.com/milahu/e1cd4aeedda84b77351cf84e10a97c07
) preprocessor
replaces the `preval` call with the return value

.... all at compile time, for "compiler side rendering"

```js
let testPreval = preval(() => ({
  a: Math.PI * 0.5,
  b: Math.sqrt(2),
}))
// --> testPreval.a = 1.5707963267948966

// unpack object properties to global scope
Object.assign(window, preval(() => ({
  a: Math.PI * 0.5,
  b: Math.sqrt(2),
})))
// --> a = 1.5707963267948966

let testPrevalFuncs = preval(()=>([
  ()=>'hello',
  ()=>('world'),
  ()=>{return 'foo'},
  function(){return 'bar'},
]))
// --> testPrevalFuncs[0] = ()=>'hello'

let testPrevalRequire = preval(() => {
  const fs = require('fs')
  return fs.readFileSync('input.txt').toString()
})
// --> testPrevalRequire = "hello world\n"

```

im using [lave](https://github.com/jed/lave) to get AST from live objects
which is a bit buggy when serializing functions

```js
() => 'result'
// is translated by lave to
eval("(() => 'result')")
```
as workaround, i added a second stage of parse-and-transform 
to remove the unneccesary eval

other "lave" implementations

* [uneval.js](https://github.com/jorendorff/sharps/blob/master/uneval.js) -- "an implementation of Mozilla's uneval function and .toSource() methods in pure ES5."  
* [decompiler.js](https://github.com/mozilla/narcissus/blob/master/lib/decompiler.js#L106) of the mozilla narcissus JS interpreter, written in JS
* https://github.com/marcello3d/node-tosource
* https://github.com/piranna/tosource-polyfill
* [uneval.js](https://gist.github.com/cheesits456/f6832a1629c0881c70ecfacafb03ff0c) gist by cheesits456
* [uneval](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/uneval) in mozilla firefox

related: 
https://github.com/kaisermann/svelte-preprocess/issues/107

any interest in using my code?
otherwise im starting a separate project

**Comment by Rich-Harris** [comment]
Thank you, but this looks like a very different project with different goals
