### ISSUE TITLE
support `import.meta`

### ISSUE THREAD

**Issue by dishuostec** [Rich-Harris/code-red#46]
Svelte will throw an error when code contains `import.meta`: https://github.com/sveltejs/svelte/issues/4379.

**Comment by Conduitry** [comment]
This is already supported in code-red if it has access to a new enough version of Acorn. (I.e., if you do a fresh install of `code-red` in a new project and automatically get the latest version of its `acorn` dependency, this will work.) Svelte's will need to be updated.
